### ISSUE TITLE
Images do not adhere to CommonMark, aren't accessible

### ISSUE THREAD

**Issue by simongray** [nextjournal/markdown#18]
Wonderful library that I get some mileage out of in separate projects, both work projects and personal ones!

However, it _does_ seem to make one promise which it can't quite hold. Specifically, in the README it says:

> (...) we adhere to [CommonMark Spec](https://spec.commonmark.org/0.30/) and also comply with extensions from [Github flavoured Markdown](https://github.github.com/gfm).

Yet the [CommonMark spec for images](https://spec.commonmark.org/0.30/#images) isn't adhered to!

# Example
For the markdown code

```markdown
![alt text](/path/to/img)
```

CommonMark specifies that the output should be

```html
<img src="/path/to/img" alt="alt text />
```

However, this library produces

```html
<figure class="image"><img src="/path/to/img" alt=""><figcaption>alt text</figcaption></figure>
```

which is probably fitting for Clerk, but it isn't the most obvious interpretation IMO and, as mentioned before, not adhering to the specification. It also doesn't provide alt text or an ARIA attribute pointing at the caption, making accessibility slightly dodgy.

# Possible solution
Adhere to the CommonMark specification (probably hard, since that would break existing users) or remove the bit that says that you do...?

**Comment by jackrusher** [comment]
Looks like a bug to me :)

**Comment by zampino** [comment]
@simongray thanks for the feedback!

I definitely agree with you 2, that the _default_ html representation should be the one suggested ([although not mandated](https://spec.commonmark.org/0.30/#about-this-document)) by the commonmark spec examples. I also don't think changing the image rendering will harm much as we don't actually use it internally (Clerk has its own renderers) and it's easy enough for folks to reimplement it back / provide their own if we change it. On this subject I hope customization of renderers is explained well enough in the README.

**Comment by simongray** [comment]
> On this subject I hope customization of renderers is explained well enough in the README.

I believe so. I immediately went and created a custom renderer to get around the issue, as I'm sure others would do too.
