### ISSUE TITLE
Doesn't support Java 22

### ISSUE THREAD

**Issue by zampino** [nextjournal/markdown#23]
As reported in Clerk https://github.com/nextjournal/clerk/issues/642. 

* https://bugs.openjdk.org/browse/JDK-8316160?subTaskView=unresolved
* https://github.com/oracle/graal/pull/7510

**Comment by AndreaCrotti** [comment]
Just encountered the same issue

**Comment by zampino** [comment]
> Just encountered the same issue

yes, still a problem, see https://github.com/nextjournal/markdown/pull/24.
