### ISSUE TITLE
removal of graalvm dependency causes build to fail

### ISSUE THREAD

**Issue by yenda** [nextjournal/markdown#31]
The removal of this line https://github.com/nextjournal/markdown/commit/75f4200961485d1db8fa36eaf6cb85fb67cfc51c#diff-551f87f7577a57c2f4f74b35056d5c7985331f7a38976810fd2bbc213bfe7bb5L4

cause my build to fail

```
Execution error (ExceptionInfo) at optimus.js/make-engine (js.clj:96).
No preferred JS engines found named ["graal.js" "rhino" "nashorn"] among available engines [com.oracle.truffle.js.scriptengine.GraalJSEngineFactory@7be3abaa]
```

I resolved it by adding that dep in my own deps.edn
not sure if this is something that should be fixed here, but I wanted to mention it in case someone got the same error and is looking for an answer after updating to the latest version

**Comment by zampino** [comment]
The point of the commit you're pointing to was exactly to get rid of GraalJS. 

Now, your exception message seems to point at this line https://github.com/magnars/optimus/blob/9629c793d554ba7b287eb43634a6b9b82258e947/src/optimus/js.clj#L96 and optimus (whatever that is) is definitely not a dependency of ours. Please check your (lein?) build and ensure it's fetching all your dependencies.
